### PR TITLE
Fix e2e test failing on missing "Reconciling with fixed duration" log message

### PR DESCRIPTION
**Pull request by n1r1**
increase test deployment grace period such that NMO controller will need to requeue after fixed duration to fix e2e tests

```release-note-none```

### CODE REVIEW

**Comment by slintes** [comment]
still flaky.... :/
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_node-maintenance-operator/148/pull-node-maintenance-operator-e2e-k8s-1.18/1346847345744023552

**Comment by n1r1** [comment]
damn.

```
          I0106 16:03:40.519898       1 nodemaintenance_controller.go:45] evicting pod node-maintenance-test/test-deployment-6b774fcff5-hpd7t
          I0106 16:03:47.528621       1 nodemaintenance_controller.go:57] pod: node-maintenance-test:test-deployment-6b774fcff5-hpd7t Evicted from node: node02
```

looks like the test-deployment being evicted too quickly despite the long grace period.
any idea why?

**Pull request merged**
