### PR TITLE
correct the namespace

### PR DESCRIPTION
**Pull request by jianzhangbjz**
Modify the CatalogSource namespace so that it can be deployed in OCP 4.2+ successfully.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by jianzhangbjz** [comment]
```release-note
It should be fixed so that others can use it easily.
```

**Comment by slintes** [comment]
Hey, sorry that this PR seems to be overseen for so long.
The namespace of the catalogsource is configured during deployment with `make cluster-sync` now:
- on k8s clusters OLM will be installed and the namespace of the CS will be `olm`
- on Openshift clusters it will be `openshift-marketplace` as you used here as well.

I only just noticed that I forgot to delete the `/olm-deploy-manifests` folder, it is unused now: templates for said files are in `/deploy` now, the processed manifests will be in `/_out` after `make cluster-sync`

For more details see #98 

Thanks!

/close

**Comment by jianzhangbjz** [comment]
@slintes Got it, thanks!

**Pull request closed without merging**
