### PR TITLE
align CI scripts with hyperconverged cluster operator.

### PR DESCRIPTION
**Pull request by MoserMichael**
**What this PR does / why we need it:**

Align CI scripts with hyperconverged cluster operator. That was the only project that I could find with a working CI for openshift 4.3 at the time of writing.

**Special notes for your reviewer:**

**Release note:**
```
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by beekhof** [comment]
I would have expected the old scripts to be removed as well

**Comment by beekhof** [comment]
@yanirq what do you think?

This is a pre-req for updating the CI jobs and adding use of node leases

**Comment by beekhof** [comment]
Need to complete the release note process

**Comment by yanirq** [comment]
> @yanirq what do you think?
> 
> This is a pre-req for updating the CI jobs and adding use of node leases

I wonder if we really need to duplicate all the code here for CI lanes. 
Maybe we can utilize [KubeVirt CI](https://github.com/kubevirt/kubevirtci/tree/master/cluster-up/cluster ) here in some way instead of duplications ? 
Adding some external possible advice here :)   @cynepco3hahue  @gbenhaim  any opinions on that matter ?

**Comment by beekhof** [comment]
@yanirq I expect that the duplication is necessary since even the HCO is doing so.

However, perhpas `git subtree` and some Makefile helpers would make the process of keeping it in sync less painful.

**Comment by MoserMichael** [comment]
I will try to work on a new PR, the proposed changes are quite profound. I am not sure that the upstream kubevirt ci works with openshift 4.x right now, but I will try. In any event we have this PR as a fallback option.

**Comment by yanirq** [comment]
You could use git-subtrees but if something breaks it could be a pitfall . just thinking out loud. 
this can be re-factored later on. just trying to think of an elegant solution

**Comment by MoserMichael** [comment]
> You could use git-subtrees but if something breaks it could be a pitfall . just thinking out loud.
> this can be re-factored later on. just trying to think of an elegant solution

why not just accept this PR as is?

**Comment by MoserMichael** [comment]
https://github.com/kubevirt/node-maintenance-operator/pull/67/ please review the PR that uses kubevirtCI.

**Comment by beekhof** [comment]
If #67 replaces this PR, please close.

**Comment by beekhof** [comment]
If #67 replaces this PR, please close.

**Pull request closed without merging**
