### PR TITLE
Add annotation to support disconnected mode

### PR DESCRIPTION
**Pull request by razo7**
Adding `'["disconnected"]'` label to `config/manifests/bases/node-maintenance-operator.clusterserviceversion.yaml` file, and then running  `make bundle` to support disconnected environment with NMO.

```release-note
Add annotation to support disconnected mode
```

### CODE REVIEW

**Comment by razo7** [comment]
\retest

**Comment by n1r1** [comment]
/ok-to-test

@razo7 you'll need to sign your commits as you previously done and also add a release notes

**Pull request merged**
