### PR TITLE
change go version to 1.15

### PR DESCRIPTION
**Pull request by mshitrit**
- go.mod updated and tidy
- Dockerfile updated
- vendor tidy

Signed-off-by: mshitrit <mshitrit@redhat.com>

```release-note updating go version from 1.13 to 1.15```

### CODE REVIEW

**Comment by slintes** [comment]
@mshitrit there are 2 more places in this repo which need to be updated:

- build/check.Dockerfile: this is used to run several code checks, see `make check`
- automation/test.sh: this is used in KubeVirtCI (does not affect the operator code, but the functest code only... however, I think we should be consistent)

Besides that, also OpenshiftCI needs to be updated: https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt/node-maintenance-operator/kubevirt-node-maintenance-operator-master.yaml#L15

**Comment by slintes** [comment]
> build/check.Dockerfile: this is used to run several code checks

this will be fixed by #151

**Comment by slintes** [comment]
> automation/test.sh

also fixed by #151 

Openshift CI: https://github.com/openshift/release/pull/14782

so all done now :slightly_smiling_face:

**Comment by mshitrit** [comment]
> Besides that, also OpenshiftCI needs to be updated: https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt/node-maintenance-operator/kubevirt-node-maintenance-operator-master.yaml#L15

is fixed in ([#14782](https://github.com/openshift/release/pull/14782))

**Pull request merged**
